### ISSUE TITLE
License information is missing

### ISSUE THREAD

**Issue by tiberiuichim** [kitconcept/volto-blocks-grid#23]
It is unclear under what license the volto-blocks-grid package is published. It would be nice to have this information, to feel safe about including this addon in custom projects.

**Comment by tisto** [comment]
@tiberiuichim the license it MIT, as Volto itself. You can see it in the package.json:

https://github.com/kitconcept/volto-blocks-grid/blob/main/package.json#L29

Though, of course, we should make this more obvious by adding a LICENSE.md and adding the license to the readme. Thanks for the hint!

**Comment by tisto** [comment]
Closing via https://github.com/kitconcept/volto-blocks-grid/pull/24
